Prevent NoClassDefFoundError during Openfire start.
f81c28b replaced org.jivesoftware.util.Log with org.slf4j.Logger.
This commit partially reverts this.

Apparently the build process produces an additional startup.jar, which contains the ServerStarter class. However, it doesn't add slf4j-api.jar to the classpath or manifest.
Because Openfire's classpath, lib folder and build structure is pretty confusing (e.g. slf4j-api.jar gets merged into a new openfire.jar, there's an extra JiveClassLoader, etc...), it's hard to solve this in a reasonable way at the moment.